name: autodqm-ml
channels:
  - conda-forge
dependencies:
  - python
  - pyaml
  - uproot
  - numpy
  - xrootd
  - rich
  - pandas
  - pyarrow
  - scipy
  - matplotlib
  - tqdm
  - sklearn
  - sphinx
  - sphinx_rtd_theme
