name: autodqm-ml
channels:
  - conda-forge
dependencies:
  - python
  - pyaml
  - uproot
  - numpy==1.21.1
  - xrootd
  - rich
  - pandas
  - pyarrow
  - scipy
  - matplotlib
  - tqdm
  - scikit-learn
  - sphinx
  - sphinx_rtd_theme
  - yahist
  - tensorflow