name: autodqm-ml
channels:
  - conda-forge
dependencies:
  - python
  - pyaml
  - uproot
  - numpy
  - xrootd
  - fsspec-xrootd
  - rich
  - pandas
  - pyarrow>=7.0.0
  - scipy
  - matplotlib
  - tqdm
  - scikit-learn
  - sphinx
  - sphinx_rtd_theme
